# Generated by Django 3.2.4 on 2021-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
