# Generated by Django 3.2.4 on 2021-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210704_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(default=0, max_length=20)),
                ('t_salary', models.IntegerField()),
            ],
        ),
    ]
