# Generated by Django 3.2.4 on 2021-07-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_authorpenname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('booked', models.ManyToManyField(to='home.book')),
            ],
        ),
    ]
